name: Run my first job
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: actions/checkout@v4
      - name: run script
        run: |
          chmod u+x hello_world.sh
          ./hello_world.sh
      
