name: Run my first job
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: actions/checkout@latest
      - name: run script
        run: |
          chmod u+x /home/runner/my-code/hello_world.sh
          ./home/runner/my-code/hello_world.sh
      
