name: Run my first job
on: [push]
jobs:
  start-conversion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: make script executable
        run: chmod u+x setupenv.sh
      - name: run the script
        run: ./setupenv.sh
      - name: convert to mp4
        run: |
         chmod u+x convert2mp4.py 
         convert2mp4.py --f urllist.txt
      
